language: cpp
compiler:
  - gcc
  - clang
# Change this to your needs
install:
  - sudo apt-get install build-essential libssl-dev libdb4.8-dev libdb4.8++-dev libboost-all-dev
script:
  - cd src/
  - make -f makefile.unix
