os: linux
language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo pip install cpp-coveralls
install: make get-deps
script:
  - ./configure --enable-gcov && make && make check
after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
notifications:
  irc: "chat.freenode.net#techcoin"
